apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5yZWRoYXQuaW8iOnsidXNlcm5hbWUiOiJoYXJzaGlrYS5yYW5hd2VlcmFAaW50aXZlLmNvbSIsInBhc3N3b3JkIjoiT3dhaW5AaXJlbGFuZDIwMjJAMSIsImVtYWlsIjoiaGFyc2hpa2EucmFuYXdlZXJhQGludGl2ZS5jb20iLCJhdXRoIjoiYUdGeWMyaHBhMkV1Y21GdVlYZGxaWEpoUUdsdWRHbDJaUzVqYjIwNlQzZGhhVzVBYVhKbGJHRnVaREl3TWpKQU1RPT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: rhdh-pull-secret
  namespace: rhdh-operator
type: kubernetes.io/dockerconfigjson
