name: Deploy SonarQube to OpenShift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      github_client_id:
        description: 'GitHub OAuth App Client ID'
        required: true
      github_client_secret:
        description: 'GitHub OAuth App Client Secret'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible kubernetes openshift

    - name: Set up OpenShift CLI
      uses: redhat-actions/oc-installer@v1
      with:
        oc_version: '4.6'

    - name: Run Ansible playbook
      env:
        GITHUB_CLIENT_ID: ${{ inputs.github_client_id != '' && inputs.github_client_id || secrets.GITHUB_CLIENT_ID }}
        GITHUB_CLIENT_SECRET: ${{ inputs.github_client_secret != '' && inputs.github_client_secret || secrets.GITHUB_CLIENT_SECRET }}
      run: |
        ansible-playbook deploy-sonarqube-operator.yml -v
