name: Run Ansible Playbook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python packages and Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible==2.10.7 kubernetes==25.3.0 openshift==0.13.1 jmespath pyyaml requests

    - name: Install Ansible collections
      run: |
        ansible-galaxy collection install kubernetes.core:==2.3.2
        ansible-galaxy collection install community.general:==6.3.0

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Install OKD CLI
      run: |
        curl -LO https://github.com/openshift/okd/releases/download/4.12.0-0.okd-2023-03-05-022504/openshift-client-linux-4.12.0-0.okd-2023-03-05-022504.tar.gz
        tar -xvf openshift-client-linux-4.12.0-0.okd-2023-03-05-022504.tar.gz
        sudo mv oc /usr/local/bin/
        sudo mv kubectl /usr/local/bin/

    - name: Run Ansible playbook in debug mode
      run: ansible-playbook rhdh-playbook.yml -vvv
      env:
        ANSIBLE_HOST_KEY_CHECKING: False