name: Run OpenShift Pipelines Ansible Playbook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-ansible-playbook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ansible and OpenShift Python client
      run: |
        python -m pip install --upgrade pip
        pip install ansible openshift

    - name: Install Ansible Galaxy collections
      run: ansible-galaxy collection install kubernetes.core community.kubernetes

    - name: Run Ansible playbook
      run: |
        ansible-playbook install-configure-pipelines-with-github-oauth.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
